### ISSUE TITLE
Ability to upload multiple closed caption files for different use cases

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt-media-autoplay#53]
Video [track](https://www.w3.org/TR/html5/semantics-embedded-content.html#the-track-element) elements can be defined by "kind" it might be useful to have kind="captions" in addition to kind="subtitles".

See https://www.w3.org/2017/04/xsmedia-tute/page4.html

**Comment by deltanetdan** [comment]
Has not been a requirement since opening, so closing.
